#!/bin/bash
#
# bootstrap and installs things.

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd -P)

echo ''

info () {
  echo -e "\r  [ \033[00;34m👀\033[0m ] $1"
}

user () {
  echo -en "\r  [ \033[10;33m💩\033[0m ] $1 "
}

success () {
  echo -e "\r\033[2K  [ \033[00;32m👍\033[0m ] $1"
}

fail () {
  echo -e "\r\033[2K  [ \033[0;31mFAIL\033[0m ] $1"
  echo ''
  exit
}

# create a new gitconfig file based on an example template
setup_gitconfig () {
  if ! [ -f git/gitconfig.local.symlink ]; then
    info 'setup gitconfig'

    git_credential='cache'

    user 'what is your github username?'
    read -e git_username
    user 'what is your github email?'
    read -e git_email

    sed -e "s/USERNAME/$git_username/g" -e "s/EMAIL/$git_email/g" -e "s/GIT_CREDENTIAL_HELPER/$git_credential/g" git/gitconfig.local.symlink.example > git/gitconfig.local.symlink

    success 'gitconfig'
  fi
}


## link file/folder, extra precautions are taken, such as avoiding original file/folder overwritten
link_file () {
  local src=$1 dst=$2

  local overwrite= backup= skip=
  local action=

  # -f returns true if file exists
  # -o returns true if the shell option opt is enabled
  # -d returns true if the file is a directory
  # -L returns true if the file is a symbolic link
  # expr1 -a expr2 returns true if expression1 and expression2 are both not null
  # expr1 -o expr2 return true if either of the expressions expr1 or expr2 are not null

  # if the destination file exists, or is a folder, or is a symbolic link
  if [ -f "$dst" -o -d "$dst" -o -L "$dst" ]
  then

    if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]
    then

      ## get the value of the original linked file
      local currentSrc="$(readlink $dst)"

      ## make sure the there is no existing linked folder
      if [ "$currentSrc" == "$src" ]
      then

        skip=true;

      else

        user "file already exists: $dst ($(basename "$src")), what do you want to do?\n\
        [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
        read -n 1 action

        case "$action" in
          o )
            overwrite=true;;
          O )
            overwrite_all=true;;
          b )
            backup=true;;
          B )
            backup_all=true;;
          s )
            skip=true;;
          S )
            skip_all=true;;
          * )
            ;;
        esac

      fi

    fi

    overwrite=${overwrite:-$overwrite_all}
    backup=${backup:-$backup_all}
    skip=${skip:-$skip_all}

    if [ "$overwrite" == "true" ]
    then
      rm -rf "$dst"
      success "removed $dst"
    fi

    if [ "$backup" == "true" ]
    then
      mv "$dst" "${dst}.backup"
      success "moved $dst to ${dst}.backup"
    fi

    if [ "$skip" == "true" ]
    then
      success "skipped $src"
    fi
  fi

  if [ "$skip" != "true" ]  # "false" or empty
  then
    ln -s "$1" "$2"
    success "linked $1 to $2"
  fi
}

install_dotfiles () {
  info 'installing dotfiles...'

  local overwrite_all=false backup_all=false skip_all=false

  ## find all the symlink ending files
  for src in $(find -H "$DOTFILES_ROOT" -maxdepth 2 -name '*.symlink' -not -path '*.git*')
  do
    ## remove the trailing suffix, i.e., symlink, and do the linking
    dst="$HOME/.$(basename "${src%.*}")"
    link_file "$src" "$dst"
  done
}


check_status_code () {
  if [ $? -eq 0 ]; then
    success "$1 is installed"
  else
    fail "error installing $1"
  fi
}

install_software () {
  info 'installing nvm...'
  curl -o- -s https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash &> /dev/null
  check_status_code "nvm"

  info 'installing node...'
  . "$HOME/.bashrc"
  . "$NVM_DIR/nvm.sh"
  nvm install node --lts &> /dev/null
  check_status_code 'node'

  info 'installing vundle...'
  git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim &> /dev/null
  check_status_code "vundle"
}

# create a new gitconfig file based on an example template
setup_gitconfig

# link all dot files
install_dotfiles

install_software

echo ''
success 'Everything is installed!'
echo ''
info "Run 'source ~/.bashrc' to activate paths and env variables!"
info "Run './script/install' to setup more softwares"
echo ''
