normal="\e[0m"
black="\e[30m"
red="\e[31m"
green="\e[32m"
yellow="\e[33m"
blue="\e[34m"
purple="\e[35m"
cyan="\e[36m"
white="\e[37m"

export PROMPT_COLOR="$purple[\t \d] $cyan\w $normal🔥\n$ "
export PROMPT_NO_COLOR="[\t \d] \w 🔥\n$ "
